# Generated by Django 2.1.15 on 2020-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_pic',
            field=models.ImageField(default='head/head_pic.jpg', upload_to='head/'),
        ),
    ]
