# Generated by Django 2.1.15 on 2020-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_head_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_pic',
            field=models.ImageField(default='h_pic/head_pic.jpg', upload_to='h_pic'),
        ),
    ]
