# Generated by Django 2.1.15 on 2020-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200228_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_pic',
            field=models.ImageField(default='head/head_pic.jpg', upload_to='head'),
        ),
    ]
