# Generated by Django 2.1.15 on 2020-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200223_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('科技', '科技'), ('游戏', '游戏'), ('影视', '影视'), ('其它', '其它')], default='QT', max_length=20),
        ),
    ]
